### ISSUE TITLE
Roadmap 🗺️

### ISSUE THREAD

**Issue by fxwiegand** [fxwiegand/predictosaurus#3]
Next tasks (in order):

- [ ] Support features on backward strand
- [ ] Improve calculation of impact and possibly find a better Impact enumeration?
- [ ] Restructure `graph.rs` file into mod with multiple files. File already has too many lines.
- [ ] Restructure calling of application into multiple subcommands:
    - 1. Build full variant graph out of vcf files and store in parquet. `preprocess`
    - 2. Retrieve subgraphs for individual features from given gff file and calculate impacts, paths etc. and store in parquet.
    - 3. Filter paths with specific impacts, allele frequencies, etc. with new interface and store again in parquet.
    - 4. Create visualizations and output HTML, TSV or vega-specs.
